#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

auto_rebuild=$(convert_bool "$YNH_APP_ARG_AUTO_REBUILD")
ynh_app_setting_set --key=auto_rebuild --value="$auto_rebuild"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

tempdir="$(mktemp -d)"

# Download, check integrity, uncompress and patch the source from manifest.toml

if [ $(lsb_release --codename --short) == 'bookworm' ]
then
    ynh_setup_source --dest_dir="$install_dir" --source_id="bookworm"
else
    ynh_setup_source --dest_dir="$install_dir"
fi

# extract the binary from the deb file
dpkg-deb -R "$install_dir/faircamp.deb" "$tempdir"

mv "$tempdir/usr/bin/faircamp" "$install_dir"

ynh_safe_rm "$tempdir"
ynh_safe_rm "$install_dir/faircamp.deb"

chmod +x "$install_dir/faircamp"

chown -R "$app:www-data" "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_setup_source --dest_dir="$install_dir/content" --source_id="website"

ynh_config_add --template="manifest.eno" --destination="$install_dir/content/catalog.eno"

mkdir -p "$install_dir/www"

chown -R "$app:www-data" "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

# adding systemd configs
ynh_config_add_systemd --service="${app}" --template="systemd.service"
ynh_config_add --template="systemd.path" --destination="/etc/systemd/system/$app.path"
systemctl daemon-reload
if $auto_rebuild; then
    systemctl enable "$app.path" --quiet
    systemctl start "$app.path"
fi

yunohost service add "$app" --description="Faircamp" --log="/var/log/$app/$app.log" --test_status="systemctl is-active $app.path"

ynh_config_add_logrotate

#=================================================
# DEFAULT WEBSITE GENERATION
#=================================================

# runned using systemctl and not a direct command line to avoid conflicting withe the '.path'
# (running two build process at the same time is buggy and can lead to errors)
systemctl start "$app.service"

# wait for the site to be builded (while the service is active, it's not done)
while (systemctl -q is-active "$app.service") do sleep 0.01; done

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
