#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

auto_rebuild=$(convert_bool "$YNH_APP_ARG_AUTO_REBUILD")
ynh_app_setting_set --app="$app" --key=auto_rebuild --value="$auto_rebuild"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

tempdir="$(mktemp -d)"

# Download, check integrity, uncompress and patch the source from manifest.toml

if [ $(lsb_release --codename --short) == 'bookworm' ]
then
    ynh_setup_source --dest_dir="$install_dir" --source_id="bookworm"
else
    ynh_setup_source --dest_dir="$install_dir"
fi

# extract the binary from the deb file
dpkg-deb -R "$install_dir/faircamp.deb" "$tempdir"

mv "$tempdir/usr/bin/faircamp" "$install_dir"

ynh_secure_remove "$tempdir"

chmod +x "$install_dir/faircamp"

### $install_dir will automatically be initialized with some decent
### permission by default ... however, you may need to recursively reapply
### ownership to all files such as after the ynh_setup_source step
chown -R "$app:www-data" "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression --message="Adding $app's configuration files..." --weight=1

mkdir -p "$install_dir/content" "$install_dir/www"

wget https://github.com/YunoHost-Apps/faircamp_ynh/releases/download/default_website/default_website.zip -P "$install_dir" 2>&1

unzip "$install_dir/default_website.zip" -d "$install_dir/content"

ynh_secure_remove "$install_dir/default_website.zip"

ynh_add_config --template="manifest.eno" --destination="$install_dir/content/catalog.eno"

chown -R "$app:www-data" "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

ynh_add_nginx_config

# adding systemd configs
ynh_add_config --template="systemd.service" --destination="/etc/systemd/system/$app.service"
ynh_add_config --template="systemd.path" --destination="/etc/systemd/system/$app.path"
systemctl daemon-reload
if $auto_rebuild; then
    systemctl enable "$app.path" --quiet
    systemctl start "$app.path"
fi

yunohost service add "$app" --description="Faircamp" --log="/var/log/$app/$app.log" --test_status="systemctl is-active $app.path"

ynh_use_logrotate

#=================================================
# DEFAULT WEBSITE GENERATION
#=================================================

# runned using systemctl and not a direct command line to avoid conflicting withe the '.path'
# (running two build process at the same time is buggy and can lead to errors)
systemctl start "$app.service"

# wait for the site to be builded (while the service is active, it's not done)
while (systemctl -q is-active "$app.service") do sleep 0.01; done

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of $app completed" --last
