#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

auto_rebuild=$(convert_bool "$YNH_APP_ARG_AUTO_REBUILD")
ynh_app_setting_set --app="$app" --key=auto_rebuild --value="$auto_rebuild"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

tempdir="$(mktemp -d)"

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

# extract the binary from the deb file
dpkg-deb -R "$install_dir/faircamp.deb" "$tempdir"

mv "$tempdir/usr/bin/faircamp" "$install_dir"

ynh_secure_remove "$tempdir"

chmod +x "$install_dir/faircamp"

### $install_dir will automatically be initialized with some decent
### permission by default ... however, you may need to recursively reapply
### ownership to all files such as after the ynh_setup_source step
chown -R "$app:www-data" "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression --message="Adding $app's configuration files..." --weight=1

ynh_add_config --template="config.toml" --destination="$install_dir/config.toml"

# FIXME: this should be handled by the core in the future
### You may need to use chmod 600 instead of 400,
### for example if the app is expected to be able to modify its own config
chmod 400 "$install_dir/config.toml"
chown "$app:$app" "$install_dir/config.toml"

mkdir -p "$install_dir/content" "$install_dir/www"

wget https://github.com/YunoHost-Apps/faircamp_ynh/releases/download/default_website/default_website.zip -P "$install_dir" 2>&1

unzip "$install_dir/default_website.zip" -d "$install_dir/content"

ynh_secure_remove "$install_dir/default_website.zip"

ynh_add_config --template="manifest.eno" --destination="$install_dir/content/manifest.eno"

chown -R "$app:www-data" "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

ynh_add_nginx_config

# adding systemd configs
ynh_add_config --template="systemd.service" --destination="/etc/systemd/system/$app.service"
ynh_add_config --template="systemd.path" --destination="/etc/systemd/system/$app.path"
systemctl daemon-reload
if $auto_rebuild; then
    systemctl enable "$app.path" --quiet
    systemctl start "$app.path"
fi

yunohost service add "$app" --description="Zola" --log="/var/log/$app/$app.log" --test_status="systemctl is-active zola.path"

ynh_use_logrotate

#=================================================
# DEFAULT WEBSITE GENERATION
#=================================================

ynh_exec_as "$app" "$install_dir/faircamp" --build-dir "$install_dir/www" --catalog-dir "$install_dir/content"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of $app completed" --last
