#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

ynh_app_setting_set_default --key=auto_rebuild --value="true"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

tempdir="$(mktemp -d)"

# Download, check integrity, uncompress and patch the source from manifest.toml
if [ $(lsb_release --codename --short) == 'bookworm' ]
then
    ynh_setup_source --dest_dir="$install_dir" --source_id="bookworm"
else
    ynh_setup_source --dest_dir="$install_dir"
fi

# extract the binary from the deb file
dpkg-deb -R "$install_dir/faircamp.deb" "$tempdir"

mv "$tempdir/usr/bin/faircamp" "$install_dir"

ynh_safe_rm "$tempdir"

chmod +x "$install_dir/faircamp"

chown -R "$app:www-data" "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

# adding systemd configs
ynh_config_add_systemd --service="${app}" --template="systemd.service"
ynh_config_add --template="systemd.path" --destination="/etc/systemd/system/$app.path"
systemctl daemon-reload
if $auto_rebuild; then
    systemctl enable "$app.path" --quiet
    systemctl start "$app.path"
else
    systemctl disable "$app.path" --quiet
    systemctl stop "$app.path"
fi

yunohost service add "$app" --description="Faircamp" --log="/var/log/$app/$app.log" --test_status="systemctl is-active $app.path"

ynh_config_add_logrotate

#=================================================
# REGENERATE WEBSITE
#=================================================

# runned using systemctl and not a direct command line to avoid conflicting withe the '.path'
# (running two build process at the same time is buggy and can lead to errors)
systemctl start "$app.service"

# wait for the site to be built (while the service is active, it's not done)
while (systemctl -q is-active "$app.service") do sleep 0.01; done

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
